import "tailwindcss/tailwind.css";
import Head from "next/head";
import { AppProps } from "next/app";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
